### PR TITLE
Added code of conduct, fixed various typos, added gitignore for node module

### PR DESCRIPTION
**Pull request by CYCLOP5**

### CODE REVIEW

**Comment by techcsispit** [comment]
Can you note all the Changes you have made?
Also note the effect of the changes and the motive behind this Pull Request.

**Comment by CYCLOP5** [comment]
- Added gitignore to ignore the nodemodules folder created when npm is initialised.

- Changed the cd 3D projects like to the actual project name in Readme file.

- Added the codeofconduct.md file which was referenced at the end of readme file which before resulted in a 404 error.

- In the work section of the webpage changed the past jobs description to past tense.

**Comment by techcsispit** [comment]
Thank you for Contributing

**Comment by CYCLOP5** [comment]
Understood, will follow that in the upcoming contributions.

**Pull request merged**
